version: '3.8'
services:
  bookmark-app-db:
    image: postgres:13
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookmarkapp-db
    networks:
      - bookmarkapp-net
networks:
  bookmarkapp-net:
